### PR TITLE
ternary version check

### PR DESCRIPTION
**Pull request by rouzbeh84**
I'm not the greatest at PHP but I think this could work to set alfred to 3 if available otherwise degrade to 2? 

would love to get this working with Alfred 3 💯

### CODE REVIEW

**Comment by afriestad** [comment]
I am also no PHP wizard, but if this correct then it is probably a better solution than #11, since it retains support for Alfred 2 :)

EDIT: On closer inspection, would the condition part not need some sort of "folder_exists()" function around it? I think it only evaluates the string right now, which will always evaluate to True.

**Comment by yannickglt** [comment]
Hey guys.
Thanks for your contribution (both of you).
I agree this PR looks better than #11 for backward compatibility.
@rouzbeh84, I think @afriestad is right and a check of the folder existence should be added to work as expected. Could you make this change before I merge the PR plz?

**Comment by rouzbeh84** [comment]
Does the ternary not work in the way expected? I have A3 so I cant test it :(

**Comment by yannickglt** [comment]
The ternary always return true because in PHP any non-empty string is a truthy value (then `"/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/"` returns true). The afriestad's proposal is to transform the ternary test into:
```php
$this->cache = $this->home. (
			file_exists("/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/") 
			?
			"/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/".$this->bundle 
			: 
			"/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/".$this->bundle
);
```

**Comment by rouzbeh84** [comment]
Ok I think that should do it for both then. Please let me know if incorrect @yannickglt

**Comment by rouzbeh84** [comment]
is there a problem with this? I can close if you like.

**Comment by yannickglt** [comment]
No tes good. Thanks for the contribution. I just need to find time to bundle the new workflow versions.

**Comment by yannickglt** [comment]
New version has been published on Packal

**Pull request merged**
